services:
  lab-notebook:
    environment:
      - AUTO_SCAN_ENABLED=${AUTO_SCAN_ENABLED:-false}
      - LAB_NOTEBOOK_READ_ONLY=${LAB_NOTEBOOK_READ_ONLY:-true}
    volumes:
      - ${DATA_DIR:-/data}:/data:rslave
    networks:
      - homelab

networks:
  homelab:
    external: true
